### PR TITLE
M changes to pull

### PR DESCRIPTION
**Pull request by matthiasreisser**
Checks if record has an ARGS field - if not, prevent crash and return sensible Validity Status:
```"Cannot Determine: Inconsistent Experiment Record"```

### CODE REVIEW

**Comment by matthiasreisser** [comment]
* because the remote file-system stuff is messed up

**Comment by petered** [comment]
do tests pass?

**Comment by petered** [comment]
merge if they do

**Comment by matthiasreisser** [comment]
Tests pass, Merging

**Pull request merged**
